# 数据源配置

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      

 datasource:
    foo:
      url: jdbc:h2:mem:foo
      username: sa
      password: 
      driver-class-name: org.h2.Driver
    
    bar:
      url: jdbc:h2:mem:bar
      username: sa
      password: 
      driver-class-name: org.h2.Driver
      
    hikari:
      # 池中维护的最小空闲连接数
      minimum-idle: 10  
      # 池中最大连接数，包括闲置和使用中的连接
      maximum-pool-size: 30 
      # 自动提交从池中返回的连接
      auto-commit: true 
      # 等待连接池分配连接的最大时长（毫秒），默认30秒
      connection-timeout: 30000 
      # 连接允许在池中闲置的最长时间，默认10分钟
      idle-timeout: 600000
      # 池中连接最长生命周期，默认30分钟 
      max-lifetime: 1800000 