package com.serendipity.cloud.orm.mybatis.model.bar.auto;

import java.io.Serializable;

public class Bar implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAR.ID
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAR.NAME
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAR.AGE
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAR.ID
     *
     * @return the value of BAR.ID
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    public Bar withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAR.ID
     *
     * @param id the value for BAR.ID
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAR.NAME
     *
     * @return the value of BAR.NAME
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    public Bar withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAR.NAME
     *
     * @param name the value for BAR.NAME
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAR.AGE
     *
     * @return the value of BAR.AGE
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    public Bar withAge(Integer age) {
        this.setAge(age);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAR.AGE
     *
     * @param age the value for BAR.AGE
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", age=").append(age);
        sb.append("]");
        return sb.toString();
    }
}