package com.serendipity.cloud.orm.mybatis.mapper.bar.auto;

import com.serendipity.cloud.orm.mybatis.model.bar.auto.Bar;
import com.serendipity.cloud.orm.mybatis.model.bar.auto.BarExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.session.RowBounds;

public interface BarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    long countByExample(BarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    int deleteByExample(BarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    @Delete({
        "delete from BAR",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    @Insert({
        "insert into BAR (NAME, AGE)",
        "values (#{name,jdbcType=VARCHAR}, #{age,jdbcType=INTEGER})"
    })
    @SelectKey(statement="CALL IDENTITY()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Bar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    int insertSelective(Bar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    List<Bar> selectByExampleWithRowbounds(BarExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    List<Bar> selectByExample(BarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    @Select({
        "select",
        "ID, NAME, AGE",
        "from BAR",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.serendipity.cloud.orm.mybatis.mapper.bar.auto.BarMapper.BaseResultMap")
    Bar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    int updateByExampleSelective(@Param("record") Bar record, @Param("example") BarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    int updateByExample(@Param("record") Bar record, @Param("example") BarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    int updateByPrimaryKeySelective(Bar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR
     *
     * @mbg.generated Fri Aug 09 14:40:06 CST 2019
     */
    @Update({
        "update BAR",
        "set NAME = #{name,jdbcType=VARCHAR},",
          "AGE = #{age,jdbcType=INTEGER}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Bar record);
}