spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      

 datasource:
    foo:
      url: jdbc:h2:mem:foo
      username: sa
      password: 
      driver-class-name: org.h2.Driver
    
    bar:
      url: jdbc:h2:mem:bar
      username: sa
      password: 
      driver-class-name: org.h2.Driver  