package com.serendipity.cloud.orm.mybatis.model.foo.auto;

import java.io.Serializable;

public class Foo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOO.ID
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOO.NAME
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FOO.AGE
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table FOO
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOO.ID
     *
     * @return the value of FOO.ID
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOO
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    public Foo withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOO.ID
     *
     * @param id the value for FOO.ID
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOO.NAME
     *
     * @return the value of FOO.NAME
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOO
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    public Foo withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOO.NAME
     *
     * @param name the value for FOO.NAME
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FOO.AGE
     *
     * @return the value of FOO.AGE
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOO
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    public Foo withAge(Integer age) {
        this.setAge(age);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FOO.AGE
     *
     * @param age the value for FOO.AGE
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FOO
     *
     * @mbg.generated Fri Aug 09 14:34:51 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", age=").append(age);
        sb.append("]");
        return sb.toString();
    }
}